name: guardian
description: Useful for ease of error management and recording unexpected errors.
version: 0.9.1
repository: https://github.com/karbunkul/dart_guardian
topics:
  - error management

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  meta: ^1.9.1
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
