name: guardian
description: A starting point for Dart libraries or applications.
version: 0.9.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
